name: Tiny partial tests emulating CI workflows

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test on ${{ matrix.os }} any testable subparts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: make test
      run: make test
